# Generated by Django 4.1 on 2023-01-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('co_name', models.CharField(max_length=20)),
                ('abstract', models.CharField(max_length=200)),
                ('team_m', models.CharField(max_length=40)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.branch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.session')),
            ],
        ),
    ]
